/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function getPacketId(data: Array<number>): number
export class LoginToken {
  identity: string
  client: string
  constructor(identity: string, client: string)
}
export class LoginPacket {
  protocolVersion: number
  tokens: LoginToken
  constructor(protocolVersion: number, tokens: LoginToken)
  static id(): number
  id(): number
  serialize(): Buffer
  static deserialize(data: Buffer): LoginPacket
}
export class ServerToClientHandshakePacket {
  token: string
  constructor(token: string)
  static id(): number
  id(): number
  serialize(): Buffer
  static deserialize(data: Buffer): ServerToClientHandshakePacket
}
export class ClientToServerHandshakePacket {
  
  constructor()
  static id(): number
  id(): number
  serialize(): Buffer
  static deserialize(data: Buffer): ClientToServerHandshakePacket
}
export class BehaviourPackInfo {
  uuid: string
  version: string
  size: bigint
  contentKey: string
  subPackName: string
  contentIdentity: string
  hasScripts: boolean
  constructor(uuid: string, version: string, size: bigint, contentKey: string, subPackName: string, contentIdentity: string, hasScripts: boolean)
}
export class ResourcePackInfo {
  uuid: string
  version: string
  size: bigint
  contentKey: string
  subPackName: string
  contentIdentity: string
  hasScripts: boolean
  rtxEnabled: boolean
  constructor(uuid: string, version: string, size: bigint, contentKey: string, subPackName: string, contentIdentity: string, hasScripts: boolean, rtxEnabled: boolean)
}
export class ResourcePacksInfoPacket {
  mustAccept: boolean
  hasScripts: boolean
  behaviourPacks: Array<BehaviourPackInfo>
  resourcePacks: Array<ResourcePackInfo>
  constructor(mustAccept: boolean, hasScripts: boolean, behaviourPacks: Array<BehaviourPackInfo>, resourcePacks: Array<ResourcePackInfo>)
  static id(): number
  id(): number
  serialize(): Buffer
  static deserialize(buf: Buffer): ResourcePacksInfoPacket
}
