// Injected types by build.js
export type VarInt = number;
export type LU16 = number;
export type LI32 = number;
export type LF32 = number;
export type U64 = bigint;
export type LittleString = string;

/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface LoginPacket {
  protocolVersion: number
  tokens: LoginTokens
}
export interface LoginTokens {
  identity: LittleString
  client: LittleString
}
export interface PlayStatusPacket {
  status: PlayStatus
}
export const enum PlayStatus {
  LoginSuccess = 0,
  FailedClient = 1,
  FailedSpawn = 2,
  PlayerSpawn = 3,
  FailedInvalidTenant = 4,
  FailedVanillaEdu = 5,
  FailedEduVanilla = 6,
  FailedServerFull = 7,
  FailedEditorVanillaMismatch = 8,
  FailedVanillaEditorMismatch = 9
}
export interface ServerToClientHandshakePacket {
  token: string
}
export interface ClientToServerHandshakePacket {
  
}
export interface DisconnectPacket {
  hideDisconnectScreen: boolean
  message: string
}
export interface ResourcePacksInfoPacket {
  mustAccept: boolean
  hasScripts: boolean
  forceServerPacks: boolean
  behaviourPacks: Array<BehaviourPackInfo>
  resourcePacks: Array<ResourcePackInfo>
}
export interface BehaviourPackInfo {
  uuid: string
  version: string
  size: U64
  contentKey: string
  subPackName: string
  contentIdentity: string
  hasScripts: boolean
}
export interface ResourcePackInfo {
  uuid: string
  version: string
  size: U64
  contentKey: string
  subPackName: string
  contentIdentity: string
  hasScripts: boolean
  rtxEnabled: boolean
}
export interface ResourcePacksStackPacket {
  mustAccept: boolean
  behaviourPacks: Array<PackIdVersion>
  resourcePacks: Array<PackIdVersion>
  gameVersion: string
  experiments: Array<Experiment>
  experimentsPreviouslyUsed: boolean
}
export interface PackIdVersion {
  uuid: string
  version: string
  name: string
}
export interface Experiment {
  name: string
  enabled: boolean
}
export interface NetworkSettingsPacket {
  compressionThreshold: LU16
  compressionAlgorithm: CompressionAlgorithm
  clientThrottle: boolean
  clientThrottleThreshold: number
  clientThrottleScalar: LF32
}
export const enum CompressionAlgorithm {
  Deflate = 0,
  Snappy = 1
}
export interface RequestNetworkSettingsPacket {
  protocolVersion: number
}
export const enum Packet {
  Login = 1,
  PlayStatus = 2,
  ServerToClientHandshake = 3,
  ClientToServerHandshake = 4,
  Disconnect = 5,
  ResourcePacksInfo = 6,
  ResourcePacksStack = 7,
  NetworkSettings = 143,
  RequestNetworkSettings = 193
}

/**
 * Injected during post build. Helps TypeScript link enum to packet type.
 */
export interface PacketEnumToPacketInjection {
  [Packet.Login]: LoginPacket;
  [Packet.PlayStatus]: PlayStatusPacket;
  [Packet.ServerToClientHandshake]: ServerToClientHandshakePacket;
  [Packet.ClientToServerHandshake]: ClientToServerHandshakePacket;
  [Packet.Disconnect]: DisconnectPacket;
  [Packet.ResourcePacksInfo]: ResourcePacksInfoPacket;
  [Packet.ResourcePacksStack]: ResourcePacksStackPacket;
  [Packet.NetworkSettings]: NetworkSettingsPacket;
  [Packet.RequestNetworkSettings]: RequestNetworkSettingsPacket;
}

// Updated by build.js
export function serialize<T extends Packet>(id: T, data: PacketEnumToPacketInjection[T]): Buffer;

// Updated by build.js
export function deserialize<T extends Packet>(id: T, data: Buffer): PacketEnumToPacketInjection[T];
export function getPacketId(data: Buffer): number
export function framePackets(packets: Array<Buffer>): Buffer
export function unframePackets(data: Buffer): Array<Buffer>
export function makeMotd(motd: string, protocolVersion: number, version: string, currentPlayers: number, maxPlayers: number, serverId: string, worldName: string, gamemode: string, gamemodeId: number, portv4: number, portv6: number): Buffer
